- 👋 Hi, I’m @SepGi
- 👀 I’m interested in IT Devops; O365; Cars
- 🌱 I’m currently learning System and Network Engineering, preffering System Engineering.
- 📫 How to reach me? You can reach me on Github and LinkedIn.
- ⚡ Fun fact: I'm a car enthousiast who wants to go on a new adventure in the world of IT.
